- .gitignore
- README.md
- learnosity_sdk/__init__.py
- learnosity_sdk/exceptions.py
- learnosity_sdk/request/__init__.py
- learnosity_sdk/request/dataapi.py
- learnosity_sdk/request/init.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/test_dataapi.py
- tests/test_init.py
- tests/test_sdk.py
- tox.ini
This adds the learnosity_sdk.request.DataApi class which provides as
convinient way to request data from Data API. In particular, it manages
the case where results could span multiple pages.
> [FEATURE] Add the DataApi request helper

- learnosity_sdk/__init__.py
- learnosity_sdk/utils/__init__.py
- learnosity_sdk/utils/lrnuuid.py
- tests/test_uuid.py
Usage:
from learnosity_sdk.utils import Uuid
print(Uuid.generate())
> [FEATURE] Added uuid utility tool

- requirements.txt
CVE-2018-18074
Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>
> [BUG] Bump requests to 2.20.0

- README.md
> [README] fixed util import path in example

- ChangeLog.md
- learnosity_sdk/request/dataapi.py
Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>
> [FEATURE] Add better context to `DataApiExceptions`s

- .codeclimate.yml
> [TEST] Add codeclimate config yml

- ChangeLog.md
- Makefile
- learnosity_sdk/request/init.py
- requirements-dev.txt
- tests/unit/test_init.py
> [FEATURE] SDK Telemetry TURTLE-59

- .travis.yml
- README.md
- learnosity_sdk/request/init.py
- tests/unit/test_init.py
> [DOCS] Clarify user_id examples CAT-77

- .travis.yml
- ChangeLog.md
- Makefile
- README.md
- learnosity_sdk/request/dataapi.py
- learnosity_sdk/request/init.py
- setup.py
- tests/unit/test_init.py
> Lrn 33360/feature/init options string

- .gitignore
- .travis.yml
- ChangeLog.md
- Makefile
- README.md
- setup.py
> [VENDOR] Update Dependencies LRN-32078

- ChangeLog.md
- learnosity_sdk/request/init.py
- tests/unit/test_init.py
> Add annotations service

- ChangeLog.md
> [Fix] Add the missing change log release LRN-36684

- learnosity_sdk/request/init.py
> [BUG] Add support for expires date in security object - LRN-41593

- ChangeLog.md
> [DOC] Add support for expires to the Change Log - LRN-41617

- README.md
> Update README.md to make image URLs absolute, for PyPi.

- ChangeLog.md
- learnosity_sdk/request/init.py
- tests/unit/test_init.py
> [FEATURE] Add authoraide key to Init Class LRN-43635

- .github/workflows/dispatch-release-pypi.yml
> [REFACTOR] Rename and update workflow to release to PyPi - LRN-43927

- .github/dependabot.yml
> [FEATURE] Add dependabot configuration

- .github/dependabot.yml
> [AIL-166] Add dependabot configuration

- .github/CODEOWNERS
Adds a base CODEOWNERS for the entire repo.
> [CONFIG] Add base CODEOWNERS file
